# Generated by Django 5.2 on 2025-05-07 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='characters/')),
                ('is_home', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('years', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('story', models.TextField(help_text='Paragrafları iki yeni satırla ayır (\\n\\n)')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='mikrop.character')),
            ],
        ),
    ]
