# Generated by Django 5.1.7 on 2025-05-07 17:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikrop', '0002_category_character_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
