# Generated by Django 5.1.7 on 2025-05-07 18:01

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrop', '0003_alter_character_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'verbose_name': 'Karakter', 'verbose_name_plural': 'Karakterler'},
        ),
        migrations.AlterModelOptions(
            name='characterdetail',
            options={'verbose_name': 'Karakter Detayı', 'verbose_name_plural': 'Karakter Detayları'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='character',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='characters', to='mikrop.category', verbose_name='Kategoriler'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Profil Resmi'),
        ),
        migrations.AlterField(
            model_name='character',
            name='is_home',
            field=models.BooleanField(default=True, verbose_name='Ana Sayfada Gösterilsin Mi?'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Karakter Adı'),
        ),
        migrations.AlterField(
            model_name='characterdetail',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='mikrop.character', verbose_name='Karakter'),
        ),
        migrations.AlterField(
            model_name='characterdetail',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Tam Adı'),
        ),
        migrations.AlterField(
            model_name='characterdetail',
            name='story',
            field=models.TextField(help_text='Paragraflar için çift enter kullanın', verbose_name='Hikaye'),
        ),
        migrations.AlterField(
            model_name='characterdetail',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='characterdetail',
            name='years',
            field=models.CharField(max_length=50, verbose_name='Yıllar'),
        ),
    ]
